# Generated by Django 4.2.3 on 2023-07-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="overallstats",
            options={"verbose_name_plural": "Overall Stats"},
        ),
        migrations.AlterModelOptions(
            name="players",
            options={"verbose_name_plural": "players"},
        ),
    ]
