# Generated by Django 4.2.3 on 2023-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_match_match_stat_delete_overallstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player_stat",
            name="season",
            field=models.CharField(max_length=32),
        ),
    ]
