# Generated by Django 4.2.3 on 2023-07-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_alter_player_stat_season"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match_stat",
            old_name="bowls_played",
            new_name="balls_played",
        ),
        migrations.AlterField(
            model_name="player_stat",
            name="season",
            field=models.CharField(max_length=30),
        ),
    ]
