# Generated by Django 4.2.3 on 2023-08-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_alter_player_stat_player"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "Matches"},
        ),
        migrations.AlterField(
            model_name="match_stat",
            name="match",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_stat",
                to="stats.match",
            ),
        ),
        migrations.AlterField(
            model_name="match_stat",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_stat",
                to="stats.player",
            ),
        ),
    ]
